services:
  - type: web
    name: youtube-talker-portfolio
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: GOOGLE_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false